apiVersion: apps/v1
kind: Deployment
metadata:
    name: fastapi-deployment
    namespace: backend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: fastapi
    template:
        metadata:
            labels:
                app: fastapi
        spec:
            nodeSelector:
                cloud.google.com/gke-nodepool: backend-pool
            containers:
                - name: fastapi
                  image: heung115/my-fastapi-app:latest
                  ports:
                      - containerPort: 8000
                  volumeMounts:
                      - name: shared-logs
                        mountPath: /app/logs
                  env:
                      - name: ENV
                        value: "production"
                      - name: LOG_PATH
                        value: "/app/logs/backend.log"
                  envFrom:
                      - secretRef:
                            name: backend-secrets
                      - configMapRef:
                            name: backend-config
                - name: log-viewer
                  image: busybox
                  command: ["sh", "-c", "tail -f /app/logs/app.log"]
                  volumeMounts:
                      - name: shared-logs
                        mountPath: /app/logs
            volumes:
                - name: shared-logs
                  persistentVolumeClaim:
                      claimName: backend-logs-pvc
