apiVersion: v1
kind: Service
metadata:
    name: fastapi-service
    namespace: backend
spec:
    type: LoadBalancer
    selector:
        app: fastapi
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
