name: Docker Build Test with Error Logging

on:
    push:
        branches:
            - feature/*

jobs:
    docker_build_test:
        name: Test Dockerfile Build
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                  install: true
            - name: Test Dockerfile Build
              id: docker_build
              run: |
                  docker build --file Dockerfile . || echo "::error::Docker build failed!"
