name: Docker Build Test with Error Logging

on:
    push:
        branches:
            - feature/*

jobs:
    docker_build_test:
        name: Test Dockerfile Build
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                  install: true

            - name: Test Dockerfile Build
              id: docker_build
              run: |
                  docker build --file Dockerfile . 2>&1 | tee build.log || echo "::set-output name=error_message::$(tail -n 10 build.log)"
              shell: bash

            - name: Notify on Failure
              if: failure()
              run: |
                  echo "Docker build failed. Sending notification..."
                  echo "Error Message: ${{ steps.docker_build.outputs.error_message }}"
                  # 알림 전송 명령어 (예: Discord 또는 이메일)
                  curl -X POST -H "Content-Type: application/json" \
                      -d '{"content": "Docker build failed with error: ```${{ steps.docker_build.outputs.error_message }}```"}' \
                      ${{ secrets.DISCORD_WEBHOOK_URL }}
